// This file was generated by tools/generate_version_headers.py, please edit version.k instead.
// Generatable header

enum {
	TR_VERSION_MAJOR = 0,
	TR_VERSION_MINOR = 4,
	TR_VERSION_PATCH = 1,
	TR_VERSION_BUILD = 580,
};
